title : Chixq:My Blog 
tagline: Blog Tagline
author :
  name : Chixq 
  email : chilaoqi@gmail.com 
  github : chilaoqi
  twitter : chisexna
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
plugins:
    google_site_verification: google7a908d88826264ac
